Align with all possible endpoints

diff --git a/.github/workflows/Everyday-ANN.yml b/.github/workflows/Everyday-ANN.yml
--- a/.github/workflows/Everyday-ANN.yml
+++ b/.github/workflows/Everyday-ANN.yml
@@ -57,8 +57,18 @@ jobs:
         # Check if predictions are present in the response
         echo $PREDICT_RESPONSE | grep -q '"predictions"' || (echo "Predictions not found in response" && exit 1)
 
+        # Predict with uploaded model ID, data file, and prediction file
+        PREDICT_RESPONSE_FILE=$(curl -s -X POST "http://127.0.0.1:8000/predict" \
+          -F "data_file=@Crop_Recommendation.csv" \
+          -F "prediction_file=@Testing_Sample.csv" \
+          -F "model_id=$MODEL_ID")
+        echo "Predict Response with prediction file: $PREDICT_RESPONSE_FILE"
+
+        # Check if predictions are present in the response
+        echo $PREDICT_RESPONSE_FILE | grep -q '"predictions"' || (echo "Predictions not found in response" && exit 1)
+
         # Train the model and get the model file
-        curl -s -F "data_file=@Crop_Recommendation.csv" -F "trial_details={\"num_epochs\":{\"high\":400}}" -F "n_trials=1" http://127.0.0.1:8000/train?return_file=true --output docker_test_model.pkl
+        curl -s -F "data_file=@Crop_Recommendation.csv" -F "trial_details={\"num_epochs\":{\"high\":400}}" -F "n_trials=10" http://127.0.0.1:8000/train?return_file=true --output docker_test_model.pkl
         echo "Model file saved as docker_test_model.pkl"
 
         # Predict with the saved model file and Crop_Recommendation.csv
@@ -70,6 +80,17 @@ jobs:
 
         # Check if predictions are present in the response
         echo $PREDICT_RESPONSE | grep -q '"predictions"' || (echo "Predictions not found in response" && exit 1)
+
+        # Predict with the saved model file and prediction file
+        PREDICT_RESPONSE_FILE=$(curl -s -X POST "http://127.0.0.1:8000/predict" \
+          -F "model_file=@docker_test_model.pkl" \
+          -F "data_file=@Crop_Recommendation.csv" \
+          -F "prediction_file=@Testing_Sample.csv")
+        echo "Predict Response with saved model and prediction file: $PREDICT_RESPONSE_FILE"
+
+        # Check if predictions are present in the response
+        echo $PREDICT_RESPONSE_FILE | grep -q '"predictions"' || (echo "Predictions not found in response" && exit 1)
+
     - name: Stop FastAPI server
       run: |
         kill $(cat uvicorn.pid)
